const vehicleConfigs = {
	defaults: {
		body: 'toyota_4runner_5g',
		lift: 0,
		color: '#c81414',
		roughness: 0,
		addons: {},
		lighting: {},
		wheel_offset: 0,
		rim: 'toyota_4runner_5thgen',
		rim_color: 'silver',
		rim_color_secondary: 'silver',
		rim_diameter: 17,
		rim_width: 10,
		tire: 'bfg_at',
		tire_diameter: 32,
		tire_muddiness: 0,
		spare: true,
	},
	vehicles: {
		toyota_4runner_5g_late: {
			slug: 'toyota-4runner-5g-late',
			name: 'Toyota 4Runner',
			year: '2014-2024',
			make: 'Toyota',
			model: '/assets/models/vehicles/toyota/4runner/5g/4runner_late.glb',
			wheel_offset: 0.8,
			wheelbase: 2.789,
			driverPosition: [0.4, 1.6, 0],
			default_addons: {},
			addons: {
				bumper_f: {
					name: 'Bumper',
					options: {
						trd_pro: {
							name: 'C4 Fabrication',
							model: '/assets/models/vehicles/toyota/4runner/5g/addons/c4_bumper.glb',
							lighting: {
								lightbar: [
									{
										name: 'Bumper Light Bar',
										width: 23,
										rows: 1,
										color: 'amber',
										position: [0, 0.255, 2.29],
										rotation: [0, 0, 0],
									},
								],
							},
						},
					},
				},
				running_boards: {
					name: 'Running Boards',
					replace: 'running_boards',
					options: {
						oem: {
							name: 'OEM',
							model: '/assets/models/vehicles/toyota/4runner/5g/addons/oem_running_boards.glb',
						},
					},
				},
				rack: {
					name: 'Roof Rack',
					replace: 'roof_rack',
					options: {
						ecotechne: {
							name: 'EcoTechne',
							model: '/assets/models/vehicles/toyota/4runner/5g/addons/ecotechne_rack.glb',
						},
					},
				},
				ladder: {
					name: 'Ladder',
					options: {
						ecotechne: {
							name: 'EcoTechne',
							model: '/assets/models/vehicles/toyota/4runner/5g/addons/ecotechne_ladder.glb',
						},
					},
				},
			},
			lighting: {
				lightbar: [
					{
						name: 'Roof Light Bar',
						width: 33,
						rows: 1,
						color: 'white',
						position: [0, 1.31, 0.575],
						rotation: [0, 0, 0],
						curvature: 3.5,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.8, 0.95, 0.875],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
		toyota_4runner_5g: {
			slug: 'toyota-4runner-5g',
			name: 'Toyota 4Runner',
			year: '2011-2013',
			make: 'Toyota',
			model: '/assets/models/vehicles/toyota/4runner/5g/4runner.glb',
			wheel_offset: 0.76,
			wheelbase: 2.789,
			driverPosition: [0.4, 1.6, 0],
			default_addons: {},
			addons: {
				rack: {
					name: 'Roof Rack',
					replace: 'roof_rack',
					options: {
						ecotechne: {
							name: 'EcoTechne',
							model: '/assets/models/vehicles/toyota/4runner/5g/addons/ecotechne_rack.glb',
							position: [0, -0.025, 0.06],
						},
					},
				},
				ladder: {
					name: 'Rear Ladder',
					options: {
						ecotechne: {
							name: 'EcoTechne',
							model: '/assets/models/vehicles/toyota/4runner/5g/addons/ecotechne_ladder.glb',
							position: [0, 0.01, 0.06],
						},
					},
				},
			},
			lighting: {
				lightbar: [
					{
						name: 'Roof Light Bar',
						width: 33,
						rows: 1,
						color: 'white',
						position: [0, 1.3, 0.575],
						rotation: [0, 0, 0],
						curvature: 2.5,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.8, 0.95, 0.875],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
		toyota_4runner_4g: {
			slug: 'toyota-4runner-4g',
			name: 'Toyota 4Runner',
			year: '2002-2009',
			make: 'Toyota',
			model: '/assets/models/vehicles/toyota/4runner/4g/4runner.glb',
			wheel_offset: 0.76,
			wheelbase: 2.79,
			driverPosition: [0.4, 1.55, -0.1],
			default_addons: {},
			addons: {},
			lighting: {
				lightbar: [
					{
						name: 'Roof Light Bar',
						width: 32,
						rows: 1,
						color: 'white',
						position: [0, 1.21, 0.385],
						rotation: [0, 0, 0],
						curvature: 10,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.75, 0.875, 0.85],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
		toyota_4runner_3g: {
			slug: 'toyota-4runner-3g',
			name: 'Toyota 4Runner',
			year: '1996-2002',
			make: 'Toyota',
			model: '/assets/models/vehicles/toyota/4runner/3g/4runner.glb',
			wheel_offset: 0.75,
			wheelbase: 2.675,
			driverPosition: [0.4, 1.55, 0],
			spare: [-0.175, 0.7, -2.5],
			default_addons: {
				bumper_f: 'stock',
				sliders: 'stock',
				rack: 'stock',
			},
			addons: {
				bumper_f: {
					name: 'Bumper',
					required: true,
					options: {
						stock: {
							name: 'Stock',
							model: '/assets/models/vehicles/toyota/4runner/3g/stock_bumper.glb',
						},
						shrockworks: {
							name: 'Shrockworks',
							model: '/assets/models/vehicles/toyota/4runner/3g/shrockworks_bumper.glb',
						},
					},
				},
				sliders: {
					name: 'Sliders',
					required: false,
					options: {
						stock: {
							name: 'Stock',
							model: '/assets/models/vehicles/toyota/4runner/3g/stock_sliders.glb',
						},
						steel: {
							name: 'Steel',
							model: '/assets/models/vehicles/toyota/4runner/3g/steel_sliders.glb',
						},
					},
				},
				rack: {
					name: 'Rack',
					required: false,
					options: {
						stock: {
							name: 'Stock',
							model: '/assets/models/vehicles/toyota/4runner/3g/stock_rack.glb',
						},
						whitson: {
							name: 'Whitson Metalworks',
							model: '/assets/models/vehicles/toyota/4runner/3g/whitson_rack.glb',
						},
					},
				},
			},
			lighting: {
				lightbar: [
					{
						name: 'Roof Light Bar',
						width: 30,
						rows: 1,
						color: 'white',
						position: [0, 1.25, 0.45],
						rotation: [0, 0, 0],
						curvature: 2,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.75, 0.85, 0.85],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
		toyota_tacoma_2g_ac: {
			slug: 'toyota-tacoma-2g',
			name: 'Toyota Tacoma',
			year: '2005-2015',
			make: 'Toyota',
			model: '/assets/models/vehicles/toyota/tacoma/2g/tacoma.glb',
			wheel_offset: 0.81,
			wheelbase: 3.245,
			driverPosition: [0.4, 1.6, 0.2],
			default_addons: {},
			addons: {},
			lighting: {
				lightbar: [
					{
						name: 'Roof Light Bar',
						width: 32,
						rows: 1,
						color: 'white',
						position: [0, 1.34, 0.66],
						rotation: [0, 0, 0],
						curvature: 2.5,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.815, 0.975, 1.075],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
		toyota_tundra_2g_crewmax: {
			slug: 'toyota-tundra-2g',
			name: 'Toyota Tundra',
			year: '2007-2021',
			make: 'Toyota',
			model: '/assets/models/vehicles/toyota/tundra/2g/tundra_crewmax.glb',
			wheel_offset: 0.85,
			wheelbase: 3.7,
			driverPosition: [0.55, 1.75, 0.3],
			default_addons: {},
			addons: {},
			lighting: {
				lightbar: [
					{
						name: 'Hood Scoop LED',
						width: 16,
						rows: 1,
						color: 'white',
						position: [0, 0.955, 2.28],
						rotation: [0, 0, 0],
						curvature: 5,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.875, 1.05, 1.4],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
		toyota_j250: {
			slug: 'toyota-land-cruiser-j250',
			name: 'Toyota Land Cruiser',
			year: '2024+',
			make: 'Toyota',
			model: '/assets/models/vehicles/toyota/land_cruiser/j250/j250.glb',
			wheel_offset: 0.81,
			wheelbase: 2.85,
			driverPosition: [0.4, 1.5, -0.1],
			default_addons: {},
			addons: {},
			lighting: {
				lightbar: [
					{
						name: 'Roof Light Bar',
						width: 32,
						rows: 1,
						color: 'white',
						position: [0, 1.3, 0.49],
						rotation: [0, 0, 0],
						curvature: 2,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.785, 0.875, 0.82],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
		toyota_j80: {
			slug: 'toyota-land-cruiser-j80',
			name: 'Toyota Land Cruiser',
			year: '1990-2008',
			make: 'Toyota',
			model: '/assets/models/vehicles/toyota/land_cruiser/j80/j80.glb',
			wheel_offset: 0.78,
			wheelbase: 2.85,
			driverPosition: [0.45, 1.7, -0.1],
			default_addons: {},
			addons: {},
			lighting: {
				lightbar: [
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.8, 0.975, 0.65],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
		jeep_jku: {
			slug: 'jeep-wrangler-jku',
			name: 'Jeep Wrangler',
			year: 'JKU',
			make: 'Jeep',
			model: '/assets/models/vehicles/jeep/jk/jku.glb',
			wheel_offset: 0.8,
			wheelbase: 2.946,
			driverPosition: [0.45, 1.65, 0],
			default_addons: {},
			addons: {
				bumper_f: {
					name: 'Bumper',
					replace: 'bumper_f',
					options: {
						motobilt_crusher: {
							name: 'Motobilt Crusher',
							model: '/assets/models/vehicles/jeep/jk/addons/motobilt_crusher_front_bumper.glb',
							position: [0, 0.31, 1.95],
						},
					},
				},
			},
			lighting: {
				lightbar: [
					{
						name: 'Roof Light Bar',
						width: 35,
						rows: 1,
						color: 'white',
						position: [0, 1.365, 0.485],
						rotation: [0, 0, 0],
						curvature: 6,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.75, 0.95, 0.7],
						rotation: [0, 0.3, 0],
						pair: true,
					},
				],
			},
		},
		jeep_yj: {
			slug: 'jeep-wrangler-yj',
			name: 'Jeep Wrangler',
			year: 'YJ',
			make: 'Jeep',
			model: '/assets/models/vehicles/jeep/yj/yj.glb',
			wheel_offset: 0.7,
			wheelbase: 2.372,
			driverPosition: [0.45, 1.65, -0.5],
			default_addons: {},
			addons: {},
			lighting: {
				lightbar: [
					{
						name: 'Roof Light Bar',
						width: 36,
						rows: 1,
						color: 'white',
						position: [0, 1.34, 0.1],
						rotation: [0, 0, 0],
						curvature: 99,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.75, 0.9, 0.3],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
		jeep_xj: {
			slug: 'jeep-cherokee-xj',
			name: 'Jeep Cherokee',
			year: 'XJ',
			make: 'Jeep',
			model: '/assets/models/vehicles/jeep/xj/xj.glb',
			wheel_offset: 0.7,
			wheelbase: 2.5,
			driverPosition: [0.45, 1.45, 0],
			default_addons: {},
			addons: {},
			lighting: {
				lightbar: [
					{
						name: 'Roof Light Bar',
						width: 30,
						rows: 1,
						color: 'white',
						position: [0, 1.15, 0.35],
						rotation: [0, 0, 0],
						curvature: 4.5,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.75, 0.775, 0.65],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
		ford_bronco_6g: {
			slug: 'ford-bronco-6g',
			name: 'Ford Bronco',
			year: '2021+',
			make: 'Ford',
			model: '/assets/models/vehicles/ford/bronco/6g/bronco.glb',
			wheel_offset: 0.85,
			wheelbase: 2.95,
			driverPosition: [0.45, 1.65, 0],
			spare: [0, 0.7, -2.35],
			default_addons: {},
			addons: {},
			lighting: {
				lightbar: [
					{
						name: 'Roof Light Bar',
						width: 32,
						rows: 1,
						color: 'white',
						position: [0, 1.355, 0.5],
						rotation: [0, 0, 0],
						curvature: 4.5,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.8, 0.93, 0.8],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
	},
	wheels: {
		rims: {
			xd_grenade: {
				make: 'XD Wheels',
				name: 'XD Series Grenade',
				model: '/assets/models/wheels/rims/xd_grenade.glb',
				width: 0.5,
				od: 1,
			},
			xd_machete: {
				make: 'XD Wheels',
				name: 'XD Machete',
				model: '/assets/models/wheels/rims/xd_machete.glb',
				width: 0.5,
				od: 1,
			},
			level_8_strike_6: {
				make: 'Level 8',
				name: 'Level 8 Strike 6',
				model: '/assets/models/wheels/rims/level_8_strike_6.glb',
				width: 0.5,
				od: 1,
			},
			konig_countersteer: {
				make: 'Konig',
				name: 'Konig Countersteer',
				model: '/assets/models/wheels/rims/konig_countersteer.glb',
				width: 0.5,
				od: 1,
			},
			cragar_soft_8: {
				make: 'Crager',
				name: 'Cragar Soft 8',
				model: '/assets/models/wheels/rims/cragar_soft_8.glb',
				width: 0.5,
				od: 1,
			},
			moto_metal_mO951: {
				make: 'Moto Metal',
				name: 'Moto Metal MO951',
				model: '/assets/models/wheels/rims/moto_metal_mO951.glb',
				width: 0.5,
				od: 1,
			},
			ar_mojave: {
				make: 'American Racing',
				name: 'American Racing Mojave',
				model: '/assets/models/wheels/rims/ar_mojave.glb',
				width: 0.5,
				od: 1,
			},
			toyota_4runner_5thgen: {
				make: 'Toyota',
				name: 'Toyota 4Runner 5th gen',
				model: '/assets/models/wheels/rims/toyota_4runner.glb',
				width: 0.5,
				od: 1,
			},
			toyota_trd: {
				make: 'Toyota',
				name: 'Toyota TRD Pro',
				model: '/assets/models/wheels/rims/toyota_trd.glb',
				width: 0.5,
				od: 1,
			},
			ford_bronco: {
				make: 'Ford',
				name: 'Ford Bronco',
				model: '/assets/models/wheels/rims/ford_bronco.glb',
				width: 0.5,
				od: 1,
			},
		},
		tires: {
			nitto_mud_grappler: {
				make: 'Nitto',
				name: 'Nitto Mud Grappler',
				model: '/assets/models/wheels/tires/mud_grappler.glb',
				width: 0.32,
				od: 0.883,
				id: 0.48,
			},
			bfg_at: {
				make: 'BFGoodrich',
				name: 'BFGoodrich A/T',
				model: '/assets/models/wheels/tires/bfg_at.glb',
				width: 0.26,
				od: 0.895,
				id: 0.43,
			},
			bfg_km3: {
				make: 'BFGoodrich',
				name: 'BFGoodrich KM3',
				model: '/assets/models/wheels/tires/bfg_km3.glb',
				width: 0.267,
				od: 0.849,
				id: 0.48,
			},
			bfg_km2: {
				make: 'BFGoodrich',
				name: 'BFGoodrich KM2',
				model: '/assets/models/wheels/tires/bfg_km2.glb',
				width: 0.245,
				od: 0.837,
				id: 0.44,
			},
			maxxis_trepador: {
				make: 'Maxxis',
				name: 'Maxxis Trepador',
				model: '/assets/models/wheels/tires/maxxis_trepador.glb',
				width: 0.34,
				od: 0.92,
				id: 0.445,
			},
		},
	},
}

export default vehicleConfigs
