let vehicleConfigs = {
  defaults: {
    id: 'toyota_4runner_5',
    lift: 0,
    color: '#B91818',
    roughness: 0,
    addons: {},
    wheel_offset: 0,
    rim: 'toyota_4runner_5thgen',
    rim_color: 'silver',
    rim_diameter: 17,
    rim_width: 10,
    tire: 'bfg_at',
    tire_diameter: 31,
    spare: false,
  },
  vehicles: {
    toyota_4runner_5: {
      name: 'Toyota 4Runner (5th gen)',
      make: 'Toyota',
      model: 'assets/models/vehicles/toyota/4runner/5g/4runner.glb',
      wheel_offset: 0.7,
      axle_front: 1.4,
      axle_rear: -1.23,
      default_addons: {},
      addons: {},
    },
    toyota_4runner_3g: {
      name: 'Toyota 4Runner (3rd gen)',
      make: 'Toyota',
      model: 'assets/models/vehicles/toyota/4runner/3g/4runner.glb',
      wheel_offset: 0.74,
      axle_front: 1.41,
      axle_rear: -1.237,
      placement: {
        spare_tire: { x: 0, y: 0.7, z: -2.45 },
      },
      default_addons: {
        bumper_f: 'stock',
        sliders: 'stock',
        rack: 'stock',
      },
      addons: {
        bumper_f: {
          name: 'Bumper',
          required: true,
          options: {
            stock: {
              name: 'Stock',
              model: 'assets/models/vehicles/toyota/4runner/3g/stock_bumper.glb',
            },
            shrockworks: {
              name: 'Shrockworks',
              model: 'assets/models/vehicles/toyota/4runner/3g/shrockworks_bumper.glb',
            },
          },
        },
        sliders: {
          name: 'Sliders',
          required: false,
          options: {
            stock: {
              name: 'Stock',
              model: 'assets/models/vehicles/toyota/4runner/3g/stock_sliders.glb',
            },
            steel: {
              name: 'Steel',
              model: 'assets/models/vehicles/toyota/4runner/3g/steel_sliders.glb',
            },
          },
        },
        rack: {
          name: 'Rack',
          required: false,
          options: {
            stock: {
              name: 'Stock',
              model: 'assets/models/vehicles/toyota/4runner/3g/stock_rack.glb',
            },
            whitson: {
              name: 'Whitson Metalworks',
              model: 'assets/models/vehicles/toyota/4runner/3g/whitson_rack.glb',
            },
          },
        },
      },
    },
    tacoma_dc_lb: {
      name: 'Toyota Tacoma (2nd gen)',
      make: 'Toyota',
      model: 'assets/models/vehicles/toyota/tacoma/2g/tacoma.glb',
      wheel_offset: 0.81,
      axle_front: 1.97,
      axle_rear: -1.59,
      default_addons: {},
      addons: {},
    },
    toyota_j80: {
      name: 'Toyota Land Cruiser (J80)',
      make: 'Toyota',
      model: 'assets/models/vehicles/toyota/land_cruiser/j80/j80.glb',
      wheel_offset: 0.78,
      axle_front: 1.545,
      axle_rear: -1.31,
      default_addons: {},
      addons: {},
    },
    jeep_jku: {
      name: 'Jeep Wrangler (JKU)',
      make: 'Jeep',
      model: 'assets/models/vehicles/jeep/jk/jku.glb',
      wheel_offset: 0.795,
      axle_front: 1.45,
      axle_rear: -1.26,
      default_addons: {},
      addons: {},
    },
    jeep_yj: {
      name: 'Jeep Wrangler (YJ)',
      make: 'Jeep',
      model: 'assets/models/vehicles/jeep/yj/yj.glb',
      wheel_offset: 0.77,
      axle_front: 1.31,
      axle_rear: -1.09,
      default_addons: {},
      addons: {},
    },
    jeep_xj: {
      name: 'Jeep Cherokee (XJ)',
      make: 'Jeep',
      model: 'assets/models/vehicles/jeep/xj/xj.glb',
      wheel_offset: 0.76,
      axle_front: 1.51,
      axle_rear: -1.24,
      default_addons: {},
      addons: {},
    },
  },
  wheels: {
    rims: {
      level_8_strike_6: {
        name: 'Level 8 Strike 6',
        model: 'assets/models/wheels/rims/level_8_strike_6.glb',
        width: 0.318,
        od: 0.488,
      },
      konig_countersteer: {
        name: 'Konig Countersteer',
        model: 'assets/models/wheels/rims/konig_countersteer.glb',
        width: 0.256,
        od: 0.47,
      },
      cragar_soft_8: {
        name: 'Cragar Soft 8',
        model: 'assets/models/wheels/rims/cragar_soft_8.glb',
        width: 0.247,
        od: 0.442,
      },
      moto_metal_mO951: {
        name: 'Moto Metal MO951',
        model: 'assets/models/wheels/rims/moto_metal_mO951.glb',
        width: 0.242,
        od: 0.407,
      },
      ar_mojave: {
        name: 'American Racing Mojave',
        model: 'assets/models/wheels/rims/ar_mojave.glb',
        width: 0.244,
        od: 0.448,
      },
      toyota_4runner_5thgen: {
        name: 'Toyota 4Runner 5th gen',
        model: 'assets/models/wheels/rims/4runner_5thgen.glb',
        width: 0.281996,
        od: 0.491841,
      },
    },
    tires: {
      nitto_mud_grappler: {
        name: 'Nitto Mud Grappler',
        model: 'assets/models/wheels/tires/mud_grappler.glb',
        width: 0.32,
        od: 0.883,
        id: 0.48,
      },
      bfg_at: {
        name: 'BFGoodrich A/T',
        model: 'assets/models/wheels/tires/bfg_at.glb',
        width: 0.26,
        od: 0.895,
        id: 0.43,
      },
      bfg_km3: {
        name: 'BFGoodrich KM3',
        model: 'assets/models/wheels/tires/bfg_km3.glb',
        width: 0.267,
        od: 0.849,
        id: 0.48,
      },
      bfg_km2: {
        name: 'BFGoodrich KM2',
        model: 'assets/models/wheels/tires/bfg_km2.glb',
        width: 0.245,
        od: 0.837,
        id: 0.44,
      },
      maxxis_trepador: {
        name: 'Maxxis Trepador',
        model: 'assets/models/wheels/tires/maxxis_trepador.glb',
        width: 0.34,
        od: 0.92,
        id: 0.445,
      },
      interco_thornbird: {
        name: 'Interco TSL Thornbird',
        model: 'assets/models/wheels/tires/thornbird.glb',
        width: 0.26,
        od: 0.871,
        id: 0.385,
      },
    },
  },
}

export default vehicleConfigs
